### ISSUE TITLE
convert to PDF with LibreOffice in Windows 10 not working

### ISSUE THREAD

**Issue by vonyang** [robsonlimadeveloper/msoffice2pdf#2]
When I used the function ```convert()```, it doesn't convert to pdf with LibreOffice, but when I enter to the ```__init__``` of ```msoffice2pdf``` I see that it should convert the file into a pdf, but it doesn't.
Here's my code:
```
from msoffice2pdf import convert    #   pip install msoffice2pdf
from os import path

word = path.abspath("mydocument.docx")
pdf = path.abspath(".")

output = convert(source = word, output_dir = pdf, soft = 1)
```

**Comment by robsonlimadeveloper** [comment]
Hello friend, sorry for my late reply. I believe you have already resolved this issue. 

Conversion using **Libreoffice** on **Windows** is important to check:

```
1. whether the source and output path are correct.
2. soft=1
3. Latest version of libreoffice.
```
